/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


-- Versao anterior:
-- DB_CHECKPOINT 6-20240828


-- Correcao da tabela tickets_treaters_stages
ALTER TABLE `tickets_treaters_stages`
MODIFY COLUMN `full_seconds` INT UNSIGNED GENERATED ALWAYS AS (TIMESTAMPDIFF(SECOND, date_start, date_stop)),
MODIFY COLUMN `hours` INT UNSIGNED GENERATED ALWAYS AS (full_seconds DIV 3600),
MODIFY COLUMN `minutes` INT UNSIGNED GENERATED ALWAYS AS ((full_seconds % 3600) DIV 60),
MODIFY COLUMN `seconds` INT UNSIGNED GENERATED ALWAYS AS ((full_seconds % 3600) % 60),
MODIFY COLUMN `concated_time` VARCHAR(15) GENERATED ALWAYS AS (
    CONCAT(
        hours,
        ':',
        LPAD(minutes, 2, '0'),
        ':',
        LPAD(seconds, 2, '0')
    )
);


-- DB_CHECKPOINT 6-20250404
INSERT INTO `config_keys` (key_name, key_value) VALUES ('DB_CHECKPOINT', '6-20250404') ON DUPLICATE KEY UPDATE id = id;
UPDATE `config_keys` SET key_value = '6-20250404' WHERE key_name = 'DB_CHECKPOINT';

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
